export default class CommonConstants {
  /**
   * 组件尺寸
   */
  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT = '100%';
  static readonly HALF_SIZE = '50%';
  static readonly CONTENT_SIZE = '95%';
  static readonly FONT_BOLDER = '700';
  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';
  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;
  /**
   * Mine tab index
   */
  static readonly  CLASSFITY_TAB_INDEX= 1;
  /**
   * Mine tab index
   */
  static readonly MINE_TAB_INDEX = 2;
  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';
  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';
  /**
   * Title text of the setting page
   */
  static readonly CLASSFITY_TITLE = '分类';

  /**
   * Title text of the setting page
   */
  static readonly MINE_TITLE = '我的';




  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;
}